import type { Metadata } from "next";
import { Cinzel, Geist, Geist_Mono } from "next/font/google";
import { HeaderSwitch } from "@/app/components/header-switch";
import { FooterSwitch } from "@/app/components/footer-switch";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const romanWoodSlideTitle = Cinzel({
  variable: "--font-rwst-stack",
  subsets: ["latin", "latin-ext"],
  weight: ["600", "700"],
});

export const metadata: Metadata = {
  title: "Play Book of burma",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${romanWoodSlideTitle.variable} h-full antialiased`}
    >
      <body className="flex min-h-full flex-col font-sans">
        <HeaderSwitch />
        <div className="flex min-h-0 flex-1 flex-col">{children}</div>
        <FooterSwitch />
      </body>
    </html>
  );
}
